### ISSUE TITLE
ES 7.*  deprecation notice on query

### ISSUE THREAD

**Issue by pkly** [handcraftedinthealps/ElasticsearchBundle#22]
When using the newest version of the bundle an error occurs when searching for a document matching something (in our case it's a simple where something_id = 1) the following error can be seen in logs

```
Deprecation ["299 Elasticsearch-7.8.0-757314695644ea9a1dc2fecd26d1a43856725e65 "[types removal] Specifying types in search requests is deprecated.""]
```

Should happen with $document = $repository->findOneBy(['whatever_id' => 5]);
PHP 7.4.14
ES 7.8.0 (docker)
Bundle 5.2.6.8

**Comment by alexander-schranz** [comment]
We relay on some deprecation methods of elasticsearch as the Bundle Supports Elastcisearch 5, 6 and 7, (8 soon) with the same version of the library. So can can ignore the deprecation which are not thrown by yourself.

**Comment by pkly** [comment]
I've long since switched to elastica but this isn't really a great practice and instead you should use slightly different queries depending on the version of ES used as to prevent hundreds of pointless errors...
