### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by Bat1stuff** [handcraftedinthealps/ElasticsearchBundle#25]
It will be great if you add symfony 6 support

**Comment by igordeveloper** [comment]
is there an estimate for SF6 supported release?

**Comment by alexander-schranz** [comment]
Support for SF6 is planned (with dropping support for PHP 7.4 and lower) but I did not have yet time to begin with it, if somebody else already want to target it feel free to create a pull request.

**Comment by alexander-schranz** [comment]
What need first be done is dropping PHP 7.4 support in https://github.com/handcraftedinthealps/ElasticsearchDSL/pull/19 and fix that PR. As said above open for contributions :)

**Comment by alexander-schranz** [comment]
Symfony 6 support was merged in #29 will be part of the next release.
